---
title: "Tables and Figures"
author: "Tyler Billings"
date: "4/29/2020"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r, include=FALSE}
library(tidyverse)
library(stargazer)
library(psych)
library(margins)
library(mfx)
library(dplyr)
library(pscl)
library(boot)
library(plyr)


#Read in the data file into an object to easily clean and analyze the data.
Adult.Pop <- read.csv(file = "c://NHISData/samadult.csv", header = TRUE, sep = ",")
Family.Pop <- read.csv(file = "c://NHISData/familyxx.csv", header = TRUE, sep = ",")

#Select only the variables that we are going to use in our analysis.
Adult.Pop1 <- dplyr::select(Adult.Pop,HHX, FMX, FPX, HRTEV, CHLYR, HYPYR1, LIVYR, KIDWKYR, JNTSYMP, PAINLMT, FLA1AR, ALCSTAT, SMKSTAT2, BMI, MODFREQW, VIGFREQW, REGION, SEX, AGE_P, RACERPI2, R_MARITL, RACERPI2)

Family.Pop1 <- dplyr::select(Family.Pop,HHX, FMX, INCGRP5)


#Remove all observations with NA values and create another summery of the data.
Adult.Pop1.Omit <- na.omit(Adult.Pop1)


#Rename our selected variables into something that is more intuitive.
#Recode qualitative variables into appropriate levels for analysis
#Remove codes that indicate an error in the questioniarre
Adult.HB <- mutate(Adult.Pop1,
                   HOUSE_NUMBER = HHX,
                   FAMILY_NUMBER = FMX,
                   PERSON_NUMBER = FPX,
                   ALCHOL_CONSUMPTION = ifelse(Adult.Pop1$ALCSTAT == 7, 1,
                                               ifelse(Adult.Pop1$ALCSTAT == 8, 1, 0)),
                   SMOKER = ifelse(Adult.Pop1$SMKSTAT2 <= 2, 1, 0),
                   BMI = ifelse(Adult.Pop1$BMI <= 9998, Adult.Pop1$BMI, NA),
                   BMI = BMI / 100,
                   MODERATE_WORKOUT = ifelse(Adult.Pop1$MODFREQW <= 28, Adult.Pop1$MODFREQW, 0),
                   VIGOROUS_WORKOUT = ifelse(Adult.Pop1$VIGFREQW <= 28, Adult.Pop1$VIGFREQW, 0),
                   REGION.NE = factor(ifelse(REGION == 1,1,0)),
                   REGION.MW = factor(ifelse(REGION == 2,1,0)),
                   REGION.SO = factor(ifelse(REGION == 3,1,0)),
                   MALE = factor(ifelse(SEX == 1,1,0)),
                   ELDERLY = factor(ifelse(Adult.Pop1$AGE_P < 65, 0, 1)),
                   OTHERRACE = factor(ifelse(RACERPI2 == 05,1,0)),
                   BLACK = factor(ifelse(RACERPI2 == 02,1,0)),
                   AIAN = factor(ifelse(RACERPI2 == 03,1,0)),
                   ASIAN = factor(ifelse(RACERPI2 == 04,1,0)),
                   MULTIPLERACE = factor(ifelse(RACERPI2 == 06,1,0)),
                   MARRIED = factor(ifelse(R_MARITL == 1,1,
                                           ifelse(R_MARITL == 2,1,0))))

#Interpret the questionaire and breakdown the dependant variables into a simple 1 or 0 to indicate if a specific chronic condition is present.
Chronic.Conditions <- data.frame(HOUSE_NUMBER = Adult.Pop$HHX,
  FAMILY_NUMBER = Adult.Pop$FMX,
  PERSON_NUMBER = Adult.Pop$FPX,
  HIGH_CHOLESTEROL = ifelse(Adult.Pop$CHLYR == 1,1,0),
  HYPERTENSION = ifelse(Adult.Pop$HYPYR1 == 1, 1, 0),
  CON_LIVER = ifelse(Adult.Pop$LIVYR == 1 , 1, 0),
  CON_KIDNEY = ifelse(Adult.Pop$KIDWKYR == 1, 1, 0),
  ASTHMA = ifelse(Adult.Pop$AASSTILL == 1, 1, 0),
  ULCER = ifelse(Adult.Pop$ULCYR == 1, 1, 0),
  BRONCHITIS = ifelse(Adult.Pop$CBRCHYR == 1, 1, 0))

#Create a new variable by adding all of the rows together to calculate the number of a persons chronic conditions. We utilize the na.rm parameter to ignore the NA values from our calculation without removing the entire row.
Chronic.Conditions <- mutate(Chronic.Conditions,
       NUMBER_CONDITIONS = rowSums(Chronic.Conditions[, -(1:3)], na.rm = TRUE))

#Combine the two sets of data (The health behaviors and the chronic conditions). Merge them based off of the House Number, Family Number, and the person Number.
Adult.Pop2 <- merge(Chronic.Conditions[, -(4:10)], Adult.HB[,-(1:13)]) #Remove the individual chronic conditions and leave only the Conditions_Number with the health behaviors
Adult.Pop2 <- dplyr::select(Adult.Pop2, NUMBER_CONDITIONS, BMI, ALCHOL_CONSUMPTION, SMOKER, MODERATE_WORKOUT, VIGOROUS_WORKOUT, MALE, ELDERLY, REGION.NE, REGION.MW, REGION.SO, BLACK, ASIAN, AIAN, MULTIPLERACE, OTHERRACE, MARRIED)

Adult.Pop1.Omit <- na.omit(Adult.Pop1)
Adult.Pop2.omit <- na.omit(Adult.Pop2)

#########################################################################################################
Adult.HB2 <- mutate(Adult.Pop1,
                    HOUSE_NUMBER = HHX,
                    FAMILY_NUMBER = FMX,
                    PERSON_NUMBER = FPX,
                    ALCHOL_CONSUMPTION = ifelse(Adult.Pop1$ALCSTAT == 7, 1,
                                                ifelse(Adult.Pop1$ALCSTAT == 8, 1, 0)),
                    SMOKER = ifelse(Adult.Pop1$SMKSTAT2 <= 2, 1, 0),
                    BMI = ifelse(Adult.Pop1$BMI <= 9998, Adult.Pop1$BMI, NA),
                    BMI = BMI / 100,
                    MODERATE_WORKOUT = ifelse(Adult.Pop1$MODFREQW <= 28, Adult.Pop1$MODFREQW, 0),
                    VIGOROUS_WORKOUT = ifelse(Adult.Pop1$VIGFREQW <= 28, Adult.Pop1$VIGFREQW, 0),
                    REGION.NE = factor(ifelse(REGION == 1,1,0)),
                    REGION.MW = factor(ifelse(REGION == 2,1,0)),
                    REGION.SO = factor(ifelse(REGION == 3,1,0)),
                    MALE = factor(ifelse(SEX == 1,1,0)),
                    ELDERLY = factor(ifelse(Adult.Pop1$AGE_P < 65, 0, 1)),
                    OTHERRACE = factor(ifelse(RACERPI2 == 05,1,0)),
                    BLACK = factor(ifelse(RACERPI2 == 02,1,0)),
                    AIAN = factor(ifelse(RACERPI2 == 03,1,0)),
                    ASIAN = factor(ifelse(RACERPI2 == 04,1,0)),
                    MULTIPLERACE = factor(ifelse(RACERPI2 == 06,1,0)),
                    MARRIED = factor(ifelse(R_MARITL == 1,1,
                                            ifelse(R_MARITL == 2,1,0))),
                    INC_LOW = factor(ifelse(RACERPI2 == 01,1,0)),
                    INC_MID  = factor(ifelse(RACERPI2 == 02,1,0)),
                    INC_MID_UP = factor(ifelse(RACERPI2 == 03,1,0)),
                    INC_UPPER = factor(ifelse(RACERPI2 == 04,1,0)))
            




Chronic.Conditions2 <- data.frame(HOUSE_NUMBER = Adult.Pop$HHX,
                                  FAMILY_NUMBER = Adult.Pop$FMX,
                                  PERSON_NUMBER = Adult.Pop$FPX,
                                  HIGH_CHOLESTEROL = ifelse(Adult.Pop$CHLYR == 1,1,0),
                                  HYPERTENSION = ifelse(Adult.Pop$HYPYR1 == 1, 1, 0),
                                  CON_LIVER = ifelse(Adult.Pop$LIVYR == 1 , 1, 0),
                                  CON_KIDNEY = ifelse(Adult.Pop$KIDWKYR == 1, 1, 0),
                                  JOINT_PAIN = ifelse(Adult.Pop$JNTSYMP == 1, 1, 0),
                                  ASTHMA = ifelse(Adult.Pop$AASSTILL == 1, 1, 0),
                                  ULCER = ifelse(Adult.Pop$ULCYR == 1, 1, 0),
                                  LIMITING_PAIN = ifelse(Adult.Pop$PAINLMT == 2 , 1,
                                                         ifelse(Adult.Pop$PAINLMT == 3 , 1,
                                                                ifelse(Adult.Pop$PAINLMT == 4, 1, 0))),
                                  FUNC_LIMIT = ifelse(Adult.Pop$FLA1AR == 1, 1, 0),
                                  BRONCHITIS = ifelse(Adult.Pop$CBRCHYR == 1, 1, 0),
                                  MIGRAINE = ifelse(Adult.Pop$AMIGR == 1, 1, 0))

#Create a new variable by adding all of the rows together to calculate the number of a persons chronic conditions. We utilize the na.rm parameter to ignore the NA values from our calculation without removing the entire row.
Chronic.Conditions2 <- mutate(Chronic.Conditions2,
                              NUMBER_CONDITIONS = rowSums(Chronic.Conditions2[, -(1:3)], na.rm = TRUE))



#Combine the two sets of data (The health behaviors and the chronic conditions). Merge them based off of the House Number, Family Number, and the person Number.
Adult.Pop3 <- merge(Chronic.Conditions2, Adult.HB2[,-(4:13)]) #Remove the individual chronic conditions and leave only the Conditions_Number with the health behaviors
Adult.Pop3 <- dplyr::select(Adult.Pop3, NUMBER_CONDITIONS, BMI, ALCHOL_CONSUMPTION, SMOKER, MODERATE_WORKOUT, VIGOROUS_WORKOUT, MALE, ELDERLY, REGION.NE, REGION.MW, REGION.SO, BLACK, ASIAN, AIAN, MULTIPLERACE, OTHERRACE, MARRIED)


Adult.Pop3.omit <- na.omit(Adult.Pop3)

```

The Summary Statistics
```{r, echo = FALSE}
#Summary Statistics for all Data
#stargazer(Adult.Pop1[,-(1:3)], type = "text",
#          title = "table 1. Descriptive Statistices (All Data)", digits = 3,
#          out = "table1.txt")

#Summary Statistics for all the tidied data 
stargazer(na.omit(Adult.Pop2), type = "text",
          title = "table 1. Descriptive Statistics (Tidied Data)", digits = 3,
          out = "table1.txt")
```

```{r, echo = FALSE}
#Add square of variables to model for quadratice independent variables
BMIsq <- Adult.Pop2.omit$BMI*Adult.Pop2.omit$BMI
VIGOROUS_WORKOUTsq <- Adult.Pop2.omit$VIGOROUS_WORKOUT*Adult.Pop2.omit$VIGOROUS_WORKOUT
MODERATE_WORKOUTsq <- Adult.Pop2.omit$MODERATE_WORKOUT*Adult.Pop2.omit$MODERATE_WORKOUT


#create the regression and summarize the results
model.ols <- lm(formula = NUMBER_CONDITIONS ~ ALCHOL_CONSUMPTION + SMOKER + log(BMI) + MODERATE_WORKOUT + MODERATE_WORKOUTsq + VIGOROUS_WORKOUT + VIGOROUS_WORKOUTsq + MALE + ELDERLY + BLACK + ASIAN + AIAN + MULTIPLERACE + OTHERRACE, data = Adult.Pop2.omit)


#Count model regression
model.count <- glm(NUMBER_CONDITIONS ~ ALCHOL_CONSUMPTION + SMOKER + log(BMI) + MODERATE_WORKOUT + MODERATE_WORKOUTsq + VIGOROUS_WORKOUT + VIGOROUS_WORKOUTsq + MALE + ELDERLY + BLACK + ASIAN + AIAN + MULTIPLERACE + OTHERRACE, family = poisson, data = Adult.Pop2.omit)

#Count model  using Quasi-Maximum Likelihood Estimator (QMLE) regression
model.qmle <- glm(NUMBER_CONDITIONS ~ ALCHOL_CONSUMPTION + SMOKER + log(BMI) + MODERATE_WORKOUT + MODERATE_WORKOUTsq + VIGOROUS_WORKOUT + VIGOROUS_WORKOUTsq + MALE + ELDERLY + BLACK + ASIAN + AIAN + MULTIPLERACE + OTHERRACE, family = quasipoisson, data = Adult.Pop2.omit)

#Count model with additional chronic conditions that are <12 mo
model.qmle2 <- glm(formula = NUMBER_CONDITIONS ~ ALCHOL_CONSUMPTION + SMOKER + log(BMI) + MODERATE_WORKOUT + MODERATE_WORKOUTsq + VIGOROUS_WORKOUT + VIGOROUS_WORKOUTsq + MALE + ELDERLY + BLACK + ASIAN + AIAN + MULTIPLERACE + OTHERRACE, family = quasipoisson, data = Adult.Pop3.omit)
```

The Correlation Matrix
```{r, echo=FALSE}
#Generate the Correlation Matrix
COR.MAT <- cor(Adult.Pop2.omit[,(1:6)], use = "complete.obs")
stargazer(COR.MAT, type = "text",
          title = "Figure 2. Correlation Matrix", digits = 3, align = TRUE,
          out = "table2.txt")
```

<p>The Dependant Variable Distribution\n</p>
```{r, echo = FALSE}
ggplot(data = Adult.Pop2.omit) +
  geom_bar(mapping = aes(x = NUMBER_CONDITIONS, y = ..count..)) +
  labs(title = "Distribution of the Dependent Variable",
       x = "Number of Chronic Conditions",
       y = "Number of Individuals",
       caption = "Figure 3.")
```

```{r,include=FALSE}
# Model significance test
gchisq.count <- model.qmle$null.deviance - model.qmle$deviance
p.gchisq.count <- pchisq(gchisq.count,df = 15, lower.tail = TRUE, log.p = TRUE)
gchisq.count
p.gchisq.count
```

Regression Models
```{r, echo = FALSE}
#Regression Results
stargazer(model.ols, model.count, model.qmle, model.qmle2, type = "text",
          title = "Table 4. Regression Results", digits = 3, align = TRUE,
          out = "table4.txt")

```

Marginal Effects
Figure 5
```{R,echo=FALSE}
(meffects1 <- poissonmfx(formula = NUMBER_CONDITIONS ~ ALCHOL_CONSUMPTION + SMOKER + log(BMI) + MODERATE_WORKOUT + MODERATE_WORKOUTsq + VIGOROUS_WORKOUT + VIGOROUS_WORKOUTsq + MALE + ELDERLY + BLACK + ASIAN + AIAN + MULTIPLERACE + OTHERRACE,atmean = FALSE, data = Adult.Pop2.omit))
```

Figure 6
```{r, echo=FALSE}
(meffects2 <- poissonmfx(formula = NUMBER_CONDITIONS ~ ALCHOL_CONSUMPTION + SMOKER + log(BMI) + MODERATE_WORKOUT + MODERATE_WORKOUTsq + VIGOROUS_WORKOUT + VIGOROUS_WORKOUTsq + MALE + ELDERLY + BLACK + ASIAN + AIAN + MULTIPLERACE + OTHERRACE,atmean = FALSE, data = Adult.Pop3.omit))
```















